name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build and Test"
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Release]

    steps:
    - uses: actions/checkout@v3

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2.2.0
      with:
         channels: conda-forge

    - name: Install conda packages
      run: conda install gtest fmt cxxopts

    - name: Install Eigen 5
      run: |
        Invoke-WebRequest -Uri "https://gitlab.com/libeigen/eigen/-/archive/5.0.0/eigen-5.0.0.zip" -OutFile "eigen-5.0.0.zip"
        Expand-Archive -Path "eigen-5.0.0.zip" -DestinationPath "."
        cd eigen-5.0.0
        cmake -B build -DBUILD_TESTING=OFF -DEIGEN_BUILD_DOC=OFF -DEIGEN_BUILD_BLAS=OFF -DEIGEN_BUILD_LAPACK=OFF
        cmake --install build --prefix "${{github.workspace}}/eigen-install"

    - name: Configure
      run: cmake -B ${{github.workspace}}/build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_PREFIX_PATH="${{github.workspace}}/eigen-install"

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure -VV
